[env:seeed_xiao_rp2040]
platform = raspberrypi
board = seeed_xiao_rp2040
framework = arduino

; Serial Monitor Baud Rate
monitor_speed = 115200

; Upload options
upload_speed = 115200

; Build flags for custom I2C pin definitions
build_flags = 
    -D SDA0_PIN=6   ; XIAO D4
    -D SCL0_PIN=7   ; XIAO D5
    -D SDA1_PIN=26  ; XIAO D0
    -D SCL1_PIN=27  ; XIAO D1